### ISSUE TITLE
Should AndroidLogcatSettings.asset be versioned?

### ISSUE THREAD

**Issue by Rabadash8820** [Unity-Technologies/com.unity.mobile.logcat#117] opened 2020-11-03 21:53 UTC
I see that the format of `AndroidLogcatSettings.asset` was changed in #107 (in fact, that Issue page is the _only_ result when Googling `"AndroidLogcatSettings.asset"` 😆). It looks like this file is now being used to store state about which devices are connected, which processes are running on those devices, whether those processes have exited, etc. However, this new behavior is creating a lot of churn in the settings file, which constantly shows up as changes in version control systems like git, and most of the new settings won't even apply on other people's machines. In other words, a lot of the contents of `AndroidLogcatSettings.asset` seems like it doesn't belong in version control.

Am I safe to .gitignore this file, or will that cause other issues for my collaborators? If not, consider this my request that some of those user-specific settings be stored elsewhere, such as the `UserSettings/` folder.

**Comment by todi1856** [comment] 2020-11-03 22:06
That's an oversight, yes, the file was intended to be committed, since it contains information about which tags you created or have selected, so you want that to persist per project. But I see how device list/process list might add a lot of noise to that.

Will try to fix that in upcoming versions, for now, yes you can safely ignore the file.

Thanks for the report

**Comment by Rabadash8820** [comment] 2020-11-03 22:14
No problem, thanks for the quick reply!

**Comment by todi1856** [comment] 2020-11-25 21:53
One more person reported this - https://forum.unity.com/threads/android-logcat-package-feedback.595003/page-2#post-6560308 just adding more info

**Closed** 2020-11-27 09:04 UTC

**Comment by Rabadash8820** [comment] 2021-01-14 03:47
@todi1856 Any idea when the Unity package will be updated with these changes?
